import { FiDownload, FiFileText } from 'react-icons/fi'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import toast from 'react-hot-toast'

function ExportButtons({ transactions, stats }) {
    const formatCurrency = (value) => {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency',
            currency: 'INR',
            maximumFractionDigits: 0,
        }).format(value)
    }

    const formatDate = (dateStr) => {
        return new Date(dateStr).toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
        })
    }

    const exportToCSV = () => {
        if (!transactions || transactions.length === 0) {
            toast.error('No transactions to export')
            return
        }

        const headers = ['Date', 'Type', 'Amount', 'Description', 'Source/Where', 'Notes']
        const rows = transactions.map((t) => [
            formatDate(t.date),
            t.type.charAt(0).toUpperCase() + t.type.slice(1),
            t.amount,
            t.description,
            t.fromWhere || '',
            t.notes || '',
        ])

        const csvContent =
            'data:text/csv;charset=utf-8,' +
            [headers.join(','), ...rows.map((r) => r.map((cell) => `"${cell}"`).join(','))].join('\n')

        const encodedUri = encodeURI(csvContent)
        const link = document.createElement('a')
        link.setAttribute('href', encodedUri)
        link.setAttribute('download', `moneyflow_transactions_${new Date().toISOString().split('T')[0]}.csv`)
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)

        toast.success('CSV exported successfully!')
    }

    const exportToPDF = () => {
        if (!transactions || transactions.length === 0) {
            toast.error('No transactions to export')
            return
        }

        const doc = new jsPDF()

        // Title
        doc.setFontSize(20)
        doc.setTextColor(14, 165, 233) // Primary blue
        doc.text('MoneyFlow Tracker', 105, 20, { align: 'center' })

        // Subtitle
        doc.setFontSize(12)
        doc.setTextColor(100)
        doc.text(`Transaction Report - ${new Date().toLocaleDateString('en-IN')}`, 105, 28, { align: 'center' })

        // Summary Section
        doc.setFontSize(14)
        doc.setTextColor(0)
        doc.text('Summary', 14, 45)

        const summaryData = [
            ['Total Income', formatCurrency(stats?.income || 0)],
            ['Total Expenses', formatCurrency(stats?.expense || 0)],
            ['Current Balance', formatCurrency(stats?.balance || 0)],
        ]

        autoTable(doc, {
            startY: 50,
            head: [['Category', 'Amount']],
            body: summaryData,
            theme: 'grid',
            headStyles: { fillColor: [14, 165, 233] },
            margin: { left: 14, right: 14 },
            tableWidth: 80,
        })

        // Transactions Table
        doc.setFontSize(14)
        doc.text('Transaction History', 14, doc.lastAutoTable.finalY + 15)

        const tableData = transactions.map((t) => [
            formatDate(t.date),
            t.type.charAt(0).toUpperCase() + t.type.slice(1),
            formatCurrency(t.amount),
            t.description,
            t.fromWhere || '-',
        ])

        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 20,
            head: [['Date', 'Type', 'Amount', 'Description', 'Source/Where']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [14, 165, 233] },
            margin: { left: 14, right: 14 },
            styles: { fontSize: 9 },
            columnStyles: {
                0: { cellWidth: 28 },
                1: { cellWidth: 22 },
                2: { cellWidth: 30 },
                3: { cellWidth: 50 },
                4: { cellWidth: 40 },
            },
        })

        // Footer
        const pageCount = doc.internal.getNumberOfPages()
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i)
            doc.setFontSize(8)
            doc.setTextColor(150)
            doc.text(
                `Page ${i} of ${pageCount} - Generated by MoneyFlow Tracker`,
                105,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            )
        }

        doc.save(`moneyflow_report_${new Date().toISOString().split('T')[0]}.pdf`)
        toast.success('PDF exported successfully!')
    }

    return (
        <div className="flex gap-3">
            <button
                onClick={exportToCSV}
                className="flex items-center gap-2 px-4 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600 transition-colors"
            >
                <FiDownload size={18} />
                <span className="hidden sm:inline">Export CSV</span>
            </button>
            <button
                onClick={exportToPDF}
                className="flex items-center gap-2 px-4 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600 transition-colors"
            >
                <FiFileText size={18} />
                <span className="hidden sm:inline">Export PDF</span>
            </button>
        </div>
    )
}

export default ExportButtons
